  // jQuery module
var _ = require('lodash');

var people = [{
  "id": 1,
  "first_name": "Elijah",
  "last_name": "Denecamp",
  "email": "edenecamp0@aol.com",
  "gender": "Male",
  "ip_address": "57.25.45.156"
}, {
  "id": 2,
  "first_name": "Trent",
  "last_name": "McMichell",
  "email": "tmcmichell1@behance.net",
  "gender": "Male",
  "ip_address": "37.66.116.219"
}, {
  "id": 3,
  "first_name": "Brooks",
  "last_name": "Besnardeau",
  "email": "bbesnardeau2@nyu.edu",
  "gender": "Female",
  "ip_address": "53.129.185.121"
}, {
  "id": 4,
  "first_name": "Doralynne",
  "last_name": "Ricardin",
  "email": "dricardin3@msn.com",
  "gender": "Female",
  "ip_address": "179.9.176.107"
}, {
  "id": 5,
  "first_name": "Jobie",
  "last_name": "Goddard",
  "email": "jgoddard4@ted.com",
  "gender": "Female",
  "ip_address": "67.196.143.82"
}, {
  "id": 6,
  "first_name": "Emilie",
  "last_name": "Mussen",
  "email": "emussen5@archive.org",
  "gender": "Female",
  "ip_address": "185.117.4.93"
}, {
  "id": 7,
  "first_name": "Cicely",
  "last_name": "Lorrie",
  "email": "clorrie6@cpanel.net",
  "gender": "Female",
  "ip_address": "22.179.204.251"
}, {
  "id": 8,
  "first_name": "Shane",
  "last_name": "Swatradge",
  "email": "sswatradge7@eepurl.com",
  "gender": "Female",
  "ip_address": "52.187.58.41"
}, {
  "id": 9,
  "first_name": "Melodie",
  "last_name": "Flintoffe",
  "email": "mflintoffe8@washington.edu",
  "gender": "Female",
  "ip_address": "214.198.125.104"
}, {
  "id": 10,
  "first_name": "Ezekiel",
  "last_name": "Meneur",
  "email": "emeneur9@boston.com",
  "gender": "Male",
  "ip_address": "76.224.115.17"
}, {
  "id": 11,
  "first_name": "Glenden",
  "last_name": "Seson",
  "email": "gsesona@wordpress.org",
  "gender": "Male",
  "ip_address": "164.129.217.143"
}, {
  "id": 12,
  "first_name": "Mariann",
  "last_name": "Whylie",
  "email": "mwhylieb@tinyurl.com",
  "gender": "Female",
  "ip_address": "79.182.208.168"
}, {
  "id": 13,
  "first_name": "Jilly",
  "last_name": "Idel",
  "email": "jidelc@ucla.edu",
  "gender": "Female",
  "ip_address": "192.33.17.32"
}, {
  "id": 14,
  "first_name": "Mace",
  "last_name": "Staig",
  "email": "mstaigd@ed.gov",
  "gender": "Male",
  "ip_address": "48.32.42.135"
}, {
  "id": 15,
  "first_name": "Adaline",
  "last_name": "Kapiloff",
  "email": "akapiloffe@patch.com",
  "gender": "Female",
  "ip_address": "45.225.28.223"
}, {
  "id": 16,
  "first_name": "Bern",
  "last_name": "Selkirk",
  "email": "bselkirkf@ibm.com",
  "gender": "Male",
  "ip_address": "92.227.12.146"
}, {
  "id": 17,
  "first_name": "Jean",
  "last_name": "Grubb",
  "email": "jgrubbg@wisc.edu",
  "gender": "Female",
  "ip_address": "22.73.81.223"
}, {
  "id": 18,
  "first_name": "Urson",
  "last_name": "Adriano",
  "email": "uadrianoh@parallels.com",
  "gender": "Male",
  "ip_address": "159.159.52.179"
}, {
  "id": 19,
  "first_name": "Denver",
  "last_name": "Nickerson",
  "email": "dnickersoni@paginegialle.it",
  "gender": "Male",
  "ip_address": "139.111.201.205"
}, {
  "id": 20,
  "first_name": "Web",
  "last_name": "Brogioni",
  "email": "wbrogionij@wordpress.org",
  "gender": "Male",
  "ip_address": "18.175.161.145"
}];

var counter = _.filter(people, {gender: 'Male'}).lenght;

alert(counter);

console.log("module 2 / lodash module is loaded.... ");