# Spring
spring:
  profiles:
    active: local
  messages:
    basename: i18n/messages
    cache-seconds: -1
    encoding: UTF-8
  application:
    name: @project.name@

# Infos Build
info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

# Logging
logging:
  path: /log/

# Endpoints
endpoints:
  shutdown:
    enabled: false
  health:
    enabled: true
    sensitive: false
  logfile:
    sensitive: false

# Management
management:
  address: ${server.address}
  port: ${server.port}
  context-path: /manage
  info:
     git:
       mode: full
  security:
    enabled: false

## Embedded Tomcat Stuff
server:
 use-forward-headers: false
 context-path: /
 port: 8080
 address: localhost
 compression:
   enabled: true
   mime-types: application/json,application/xml,text/html,text/xml,text/plain

